name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/lighthouse:$(date +s%)
    
    - name: Docker Push
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
      run: docker push ${{secrets.DOCKERHUB_USER}}/lighthouse:$(date +s%)
